spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          brokers: 10.0.3.176:9092
          zkNodes: 10.0.3.176:2181

review-service:
  ribbon:
    listOfServers: review-service.default.alcatraz.local:8082